import "./globals.css";
import { Navbar2 } from "@/components/navbar-02";
import { Footer4 } from "@/components/footer-04";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navbar2 />
        {children}
        <Footer4 />
      </body>
    </html>
  );
}
